### PR TITLE
Wokwi simulation setup

### PR DESCRIPTION
**Pull request by urish**
See wokwi/wokwi-esp-test-template#1 for context

### CODE REVIEW

**Comment by tomassebestik** [comment]
@urish This looks great, thank you for this PR. It would be nice to have both HW and Wokwi simulation testing in one Espressif repo.

LGTM!

**Review by tomassebestik — APPROVED** [review]

**Review by pedrominatel — APPROVED** [review]
Thanks @urish! This is a nice topic for an article at our Developer Portal.

**Comment by urish** [comment]
Thanks! I'm still working on my talk for DevCon 24 (shhh don't tell anyone it's not ready yet...), and I'm going to mention it there too

**Comment by VojtechBartoska** [comment]
> Thanks! I'm still working on my talk for DevCon 24 (shhh don't tell anyone it's not ready yet...), and I'm going to mention it there too

we are everywhere 👯‍♂️

**Pull request merged**
